# Generated by Django 3.2.4 on 2021-07-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nombre_apellido', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre_apellido')),
                ('correo', models.CharField(max_length=150, verbose_name='Correo')),
                ('mensaje', models.CharField(max_length=150, verbose_name='mensaje')),
                ('tipo_consulta', models.CharField(max_length=50, verbose_name='Tipo_consulta')),
            ],
        ),
    ]
